import { IUser } from '../models/IUser.model';

export const DEFAULT_USER_DATA: IUser = {
  id: 1,
  name: 'Agustin',
  lastName: 'Collueque Velazquez',
  title: 'Web Developer',
  mainPhrase:
    'I like to create robust and scalable web applications with the best user experiences.',
  secondaryPhrase:
    'Passionate about constant learning and creative solutions that make a difference.',
  description:
    'I enjoy creating web applications that not only work well, but are carefully designed from the inside out. I have a special love for backend development with Java, where I focus on writing clean, maintainable code, good architecture, and proven design patterns. I care about the details, from how data flows to how users feel, combining depth and technique with a human touch.',
  email: 'agustincv1997@gmail.com',
  age: 27,
  urlImg: 'assets/img/perfil-default.jpeg',
  urlCV: 'assets/CV_AGUSTIN.pdf',
  projects: [
    {
      id: 1,
      title: 'Portfolio Web',
      description:
        'Personal site to show projects, skills and track record as a web developer, with responsive design and fluid navigation.',
      link: '#',
      urlImg: 'assets/img/projects/portfolio-web.png',
      startDate: '2025-04-20',
      endDate: '2025-07-27',
      tecnologies: [],
    },
    {
      id: 2,
      title: 'Tournament Manager App',
      description:
        'Complete application to manage sports tournaments, with team management, fixture, statistics and user control.',
      link: '#',
      urlImg: 'assets/img/projects/tournament-manager.png',
      startDate: '2025-04-20',
      endDate: '2025-08-12',
      tecnologies: [],
    },
  ],
  jobs: [
    {
      id: 1,
      title: 'Barbershop Shift Management',
      description:
        'Web application to schedule appointments, advertise, control services and clients, with an administration panel.',
      urlImg: 'assets/img/projects/shift-manager.png',
      startDate: '2025-08-12',
      endDate: 'Currently',
      technologies: [],
    },
  ],
  formations: [
    {
      id: 1,
      title: 'Web Full Stack Junior',
      description:
        'Comprehensive training in web development, with a focus on frontend and backend technologies. Practices in responsive design, API consumption, authentication, version control and cloud deployment. Development of a personal portfolio project following agile methodologies.',
      startDate: '2022-11-16',
      endDate: '2023-08-22',
      type: 'CURSO',
      academy: 'National Institute of Industrial Technology',
      skills: [],
    },
    {
      id: 2,
      title: 'Technical English for software developers',
      description:
        'Oral/written comprehension and production in everyday situations. Practice essential vocabulary, simple grammatical structures and communication skills for personal presentations, descriptions, requests and understanding of basic instructions.',
      startDate: '2023-08-25',
      endDate: '2023-10-22',
      type: 'CURSO',
      academy: 'University Language Center',
      skills: [],
    },
    {
      id: 3,
      title: "Bachelor's degree in computer science",
      description:
        'Oral/written comprehension and production in everyday situations. Practice essential vocabulary, simple grammatical structures and communication skills for personal presentations, descriptions, requests and understanding of basic instructions.',
      startDate: '2015-03-08',
      endDate: 'Actually',
      type: 'FORMACION_FORMAL',
      academy: 'National University of Comahue',
      skills: [],
    },
  ],
  skills: [
    {
      id: 1,
      name: 'HTML5',
      skills: ['Semantic', 'Accesibility', 'Multimedia Labels'],
      urlLogo: 'assets/img/logos/language/html5.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 2,
      name: 'CSS3',
      skills: ['Flexbox', 'Grid', 'Responsive Design'],
      urlLogo: 'assets/img/logos/language/css_old.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 3,
      name: 'JavaScript',
      skills: ['DOM Manipulation', 'Events', 'Async/Await Functions'],
      urlLogo: 'assets/img/logos/language/javascript.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 4,
      name: 'TypeScript',
      skills: ['Static typing', 'Interfaces', 'Decorators'],
      urlLogo: 'assets/img/logos/language/typescript.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 5,
      name: 'Java',
      skills: ['POO', 'Collections', 'Streams', 'Lambdas'],
      urlLogo: 'assets/img/logos/language/java.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 6,
      name: 'JSON',
      skills: ['Exchange format', 'APIs REST', 'Serialization'],
      urlLogo: 'assets/img/logos/language/json.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 7,
      name: 'Angular',
      skills: [
        'Components/Moduls',
        'Services',
        'Routes',
        'Standalone Components',
      ],
      urlLogo: 'assets/img/logos/framework/angular.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 8,
      name: 'RxJS',
      skills: ['Observables', 'Subjects', 'Operators'],
      urlLogo: 'assets/img/logos/library/rxjs.svg',
      isLearning: false,
      type: 'LIBRARY',
    },
    {
      id: 9,
      name: 'Spring Boot',
      skills: ['REST API', 'JPA', 'Security', 'Dependency Injection'],
      urlLogo: 'assets/img/logos/framework/spring.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 10,
      name: 'Bootstrap',
      skills: ['UI Components', 'Flexbox/Grid', 'Utilities'],
      urlLogo: 'assets/img/logos/framework/bootstrap.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 11,
      name: 'Tailwind CSS',
      skills: ['Utility-First', 'Responsive', 'Customization'],
      urlLogo: 'assets/img/logos/framework/tailwindcss.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 12,
      name: 'Git',
      skills: ['Commits', 'Branching', 'Merge', 'Rebase'],
      urlLogo: 'assets/img/logos/tool/git.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 13,
      name: 'GitHub',
      skills: ['Remote Repositories', 'Pull Requests', 'Actions'],
      urlLogo: 'assets/img/logos/platform/github.svg',
      isLearning: false,
      type: 'PLATFORM',
    },
    {
      id: 14,
      name: 'PostgreSQL',
      skills: ['SQL Queries', 'Relational Modeling', 'Indexs'],
      urlLogo: 'assets/img/logos/database/postgresql.svg',
      isLearning: false,
      type: 'DATABASE',
    },
    {
      id: 15,
      name: 'MySQL',
      skills: ['SQL Queries', 'Stored Procedures', 'Integration with JPA'],
      urlLogo: 'assets/img/logos/database/mysql.svg',
      isLearning: false,
      type: 'DATABASE',
    },
    {
      id: 16,
      name: 'NetBeans',
      skills: ['Java Development', 'Debugging', 'Maven'],
      urlLogo: 'assets/img/logos/ide/netbeans.svg',
      isLearning: false,
      type: 'IDE',
    },
    {
      id: 17,
      name: 'VS Code',
      skills: ['Extensions', 'Snippets', 'Code Debugging'],
      urlLogo: 'assets/img/logos/ide/vscode.svg',
      isLearning: false,
      type: 'IDE',
    },
    {
      id: 18,
      name: 'Docker',
      skills: ['Images', 'Containers', 'Docker Compose'],
      urlLogo: 'assets/img/logos/tool/docker.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 19,
      name: 'npm',
      skills: ['Package Installation', 'Scripts', 'Dependency Management'],
      urlLogo: 'assets/img/logos/tool/npm.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 20,
      name: 'Swagger',
      skills: ['Apis Documentation', 'OpenAPI', 'Interactive UI'],
      urlLogo: 'assets/img/logos/tool/swagger.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 21,
      name: 'JWT Token',
      skills: ['Authentication', 'Claims', 'Token Validation'],
      urlLogo: 'assets/img/logos/security/jwt.svg',
      isLearning: false,
      type: 'SECURITY',
    },
    {
      id: 22,
      name: 'Auth0',
      skills: ['Identity Management', 'OAuth', 'Single Sign-On'],
      urlLogo: 'assets/img/logos/security/auth0.svg',
      isLearning: true,
      type: 'SECURITY',
    },
    {
      id: 23,
      name: 'Postman',
      skills: ['API Testing', 'Collections', 'Environment Variables'],
      urlLogo: 'assets/img/logos/tool/postman.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 24,
      name: 'jQuery',
      skills: ['DOM Manipulation', 'Events', 'AJAX'],
      urlLogo: 'assets/img/logos/library/jquery.svg',
      isLearning: false,
      type: 'LIBRARY',
    },
    {
      id: 25,
      name: 'Node.js',
      skills: ['Event Loop', 'Express Integration', 'npm Modules'],
      urlLogo: 'assets/img/logos/platform/nodejs.svg',
      isLearning: false,
      type: 'PLATFORM',
    },
    {
      id: 26,
      name: 'Prettier',
      skills: ['Code Formatting', 'Integration with Editors', 'Custom Rules'],
      urlLogo: 'assets/img/logos/tool/prettier.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 27,
      name: 'Express.js',
      skills: ['Routing', 'Middlewares', 'REST APIs'],
      urlLogo: 'assets/img/logos/framework/expressjs.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
  ],
  yearsXP: 3,
  numberPhone: '2944-716770',
};
