import { IUser } from '../models/IUser.model';

export const DEFAULT_USER_DATA: IUser = {
  id: 1,
  name: 'Agustin',
  lastName: 'Collueque Velazquez',
  title: 'Desarrollador Web',
  mainPhrase:
    'Feliz de ayudarte a resolver problemas (con un poco de código) y aprender algo nuevo en el camino.',
  secondaryPhrase:
    'Apasionado por el aprendizaje constante y las soluciones creativas que marcan la diferencia.',
  description:
    "Soy Desarrollador Web Full Stack con una base sólida en programación. Estoy en constante aprendizaje y evolución, siempre buscando mejorar mis habilidades. Disfruto compartiendo lo que sé con quienes recién comienzan en este apasionante mundo de la programación, intercambiando ideas, debatiendo enfoques y creciendo junto a la comunidad. Disfruto creando aplicaciones web que no sólo funcionen bien, sino que estén cuidadosamente diseñadas de adentro hacia afuera. Me concentro en escribir código limpio y mantenible, buena arquitectura y patrones de diseño probados. Me importan los detalles, desde cómo fluyen los datos hasta cómo se sienten los usuarios, combinando profundidad y técnica con un toque humano.",
  email: 'agustincv1997@gmail.com',
  age: 27,
  urlImg: 'assets/img/prophile-default.webp',
  urlCV: 'assets/cv-agustin-collueque.pdf',
  projects: [
    {
      id: 1,
      title: 'Portfolio Web',
      description:
        'Aplicación Web personal diseñada para mostrar mis trabajos como desarrollador, mis proyectos destacados, experiencia en tecnologías, formación académica y otras cosas interesantes sobre mí.',
      link: '#',
      urlImg: 'assets/img/projects/portfolio-web.png',
      startDate: '2025-06-03',
      endDate: '2025-07-27',
      tecnologies: [],
    },
    {
      id: 2,
      title: 'Gestor de Torneos de Fútbol',
      description:
        'Aplicación completa para gestionar torneos deportivos, con gestión de equipos, partidos, estadísticas y control de usuarios.',
      link: '#',
      urlImg: 'assets/img/projects/tournament-manager.png',
      startDate: '2025-04-20',
      endDate: '2025-08-12',
      tecnologies: [],
    },
    {
      id: 1,
      title: 'Portfolio Web',
      description:
        'Aplicación Web personal diseñada para mostrar mis trabajos como desarrollador, mis proyectos destacados, experiencia en tecnologías, formación académica y otras cosas interesantes sobre mí.',
      link: '#',
      urlImg: 'assets/img/projects/portfolio-web.png',
      startDate: '2025-06-03',
      endDate: '2025-07-27',
      tecnologies: [],
    },
    {
      id: 2,
      title: 'Gestor de Torneos de Fútbol',
      description:
        'Aplicación completa para gestionar torneos deportivos, con gestión de equipos, partidos, estadísticas y control de usuarios.',
      link: '#',
      urlImg: 'assets/img/projects/tournament-manager.png',
      startDate: '2025-04-20',
      endDate: '2025-08-12',
      tecnologies: [],
    },
  ],
  jobs: [
    {
      id: 1,
      title: 'Gestor de Turnos Barbería',
      description:
        'Aplicación Web para gestionar turnos de una barbería/peluquería, con gestión de usuarios y clientes.',
      urlImg: 'assets/img/projects/shift-manager.png',
      startDate: '2025-08-06',
      endDate: 'Actualidad.',
      technologies: [],
    },
  ],
  formations: [
    {
      id: 1,
      title: 'Desarrollador Web FullStack',
      description:
        'Capacitación integral en desarrollo web, con enfoque en tecnologías frontend y backend. Prácticas en diseño responsivo, consumo de API, autenticación, control de versiones e implementación en la nube. Desarrollo de un proyecto de portfolio personal siguiendo buenas prácticas y metodologías ágiles.',
      startDate: '2022-11-16',
      endDate: '2023-08-22',
      type: 'CURSO',
      academy: 'Instituto Nacional de Tecnología Industrial (INTI)',
      technologies: [],
    },
    {
      id: 2,
      title: 'Inglés Técnico para Programadores',
      description:
        'Comprensión y producción oral/escrita en situaciones cotidianas. Práctica de vocabulario esencial, estructuras gramaticales simples y habilidades de comunicación para presentación personal, descripciones, solicitudes y comprensión de instrucciones básicas.',
      startDate: '2023-08-25',
      endDate: '2023-10-22',
      type: 'CURSO',
      academy: 'Centro Universitario de Idiomas (CUI)',
      technologies: [],
    },
    {
      id: 3,
      title: "Licenciatura en Ciencias de la Computación",
      description:
        'Aprendí conceptos esenciales como Arquitectura de Software, Patrones de Diseño y Paradigmas de Programación, que puedo aplicar de manera eficaz. Además de otros temas como los principios SOLID, separación de responsabilidades y buenas prácticas para el desarrollo de sistemas escalables y mantenibles, aprendí valores como la resiliencia, al enfrentar desafíos técnicos y personales que me ayudaron a crecer. También desarrollé habilidades como el trabajo en equipo, la comunicación efectiva, la organización del tiempo y la capacidad de autogestión, que hoy aplico tanto en proyectos individuales como colaborativos. Esta etapa me preparó no solo para programar, sino también para adaptarme a los cambios, mantener una mentalidad de mejora continua y disfrutar el proceso de aprender cada día algo nuevo. Sigo formándome con pasión, motivado por la curiosidad y el deseo de construir soluciones que realmente aporten valor.',
      startDate: '2015-03-08',
      endDate: '2020-03-08',
      type: 'FORMACION_FORMAL',
      academy: 'Universidad Nacional del Comahue',
      technologies: [],
    },
  ],
  skills: [
    {
      id: 1,
      name: 'HTML5',
      skills: ['Sintaxis', 'Semántica', 'Accesibilidad', 'Media Queries', 'Metaetiquetas y Microdatos', 'APIs del navegador', 'Buenas Prácticas'],
      urlLogo: 'assets/img/logos/language/html5.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 2,
      name: 'CSS3',
      skills: ['Flexbox', 'Grid Layout', 'Diseño Responsivo', 'Animaciones y Transiciones', 'Selectores', 'Web Fonts', 'Mejoras para SEO y Rendimiento'],
      urlLogo: 'assets/img/logos/language/css_old.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 3,
      name: 'JavaScript',
      skills: ['Manipulación del DOM', 'Eventos', 'Funciones Async/Await', 'Interactividad del Usuario', 'AJAX/FETCH', 'Almacenamiento Local', 'Lógica de Programación', 'Integración con APIs','SSR/SSG', 'Seguridad'],
      urlLogo: 'assets/img/logos/language/javascript.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 4,
      name: 'TypeScript',
      skills: ['Tipado Genérico y Personalizado', 'Interfaces', 'Decoradores', 'Literales de tipo', 'Union, Intersección y Mapeos', 'Enums', 'POO'],
      urlLogo: 'assets/img/logos/language/typescript.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 5,
      name: 'Java',
      skills: ['POO', 'Collections', 'Streams', 'Lambdas', 'Tipados Genéricos'],
      urlLogo: 'assets/img/logos/language/java.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 6,
      name: 'JSON',
      skills: ['Acceso y manipulación', 'APIs REST', 'Serialización', 'Buenas Prácticas', 'Peticiones HTTP'],
      urlLogo: 'assets/img/logos/language/json.svg',
      isLearning: false,
      type: 'LANGUAGE',
    },
    {
      id: 7,
      name: 'Angular',
      skills: [
        'Módulos/Componentes', 'Angular Directives', 'Enrutamiento Avanzado', 'Karma/Protractor', 'Componentes Standalone', 'Data Binding', 'Inyección de Dependencias'
      ],
      urlLogo: 'assets/img/logos/framework/angular.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 8,
      name: 'RxJS',
      skills: ['Observables', 'Subscriptions', 'Subjects', 'Operators', 'Pipes'],
      urlLogo: 'assets/img/logos/library/rxjs.svg',
      isLearning: false,
      type: 'LIBRARY',
    },
    {
      id: 9,
      name: 'Spring Boot',
      skills: ['REST API', 'JPA', 'Hibernate', 'Spring Web', 'Spring Security', 'Inyeccion de Dependencias', 'Lombok', 'Anotaciones', 'Testing'],
      urlLogo: 'assets/img/logos/framework/spring.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 10,
      name: 'Bootstrap',
      skills: ['UI Components', 'Flexbox/Grid', 'Utilidades', 'Integración con Popper.js'],
      urlLogo: 'assets/img/logos/framework/bootstrap.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 11,
      name: 'Tailwind CSS',
      skills: ['Utility-First', 'Diseño Responsive', 'Personalización'],
      urlLogo: 'assets/img/logos/framework/tailwindcss.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
    {
      id: 12,
      name: 'Git',
      skills: ['Commits', 'Branching', 'Merge', 'Rebase'],
      urlLogo: 'assets/img/logos/tool/git.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 13,
      name: 'GitHub',
      skills: ['Remote Repositories', 'Pull Requests', 'Actions'],
      urlLogo: 'assets/img/logos/platform/github.svg',
      isLearning: false,
      type: 'PLATFORM',
    },
    {
      id: 14,
      name: 'PostgreSQL',
      skills: ['SQL Queries', 'Modelo Relacional', 'Índices'],
      urlLogo: 'assets/img/logos/database/postgresql.svg',
      isLearning: false,
      type: 'DATABASE',
    },
    {
      id: 15,
      name: 'MySQL',
      skills: ['SQL Queries', 'Stored Procedures', 'Integración con JPA'],
      urlLogo: 'assets/img/logos/database/mysql.svg',
      isLearning: false,
      type: 'DATABASE',
    },
    {
      id: 16,
      name: 'NetBeans',
      skills: ['Java Development', 'Debugging', 'Maven'],
      urlLogo: 'assets/img/logos/ide/netbeans.svg',
      isLearning: false,
      type: 'IDE',
    },
    {
      id: 17,
      name: 'VS Code',
      skills: ['Plugins', 'Snippets', 'Code Debugging'],
      urlLogo: 'assets/img/logos/ide/vscode.svg',
      isLearning: false,
      type: 'IDE',
    },
    {
      id: 18,
      name: 'Docker',
      skills: ['Images', 'Containers', 'Docker Compose', 'Comandos', 'Docker Desktop'],
      urlLogo: 'assets/img/logos/tool/docker.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 19,
      name: 'npm',
      skills: ['Instalación de paquetes', 'Scripts', 'Gestión de Dependencias'],
      urlLogo: 'assets/img/logos/tool/npm.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 20,
      name: 'Swagger',
      skills: ['Uso de UI'],
      urlLogo: 'assets/img/logos/tool/swagger.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 21,
      name: 'JWT Token',
      skills: ['Authenticación', 'Claims', 'Validación de Token'],
      urlLogo: 'assets/img/logos/security/jwt.svg',
      isLearning: false,
      type: 'SECURITY',
    },
    {
      id: 22,
      name: 'Auth0',
      skills: ['Gestión de Identidad', 'OAuth', 'Único Sign-On'],
      urlLogo: 'assets/img/logos/security/auth0.svg',
      isLearning: true,
      type: 'SECURITY',
    },
    {
      id: 23,
      name: 'Postman',
      skills: ['API Testing', 'Formato JSON', 'Variables de entorno'],
      urlLogo: 'assets/img/logos/tool/postman.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 24,
      name: 'jQuery',
      skills: ['DOM', 'Eventos', 'AJAX', 'JS', 'CSS'],
      urlLogo: 'assets/img/logos/library/jquery.svg',
      isLearning: false,
      type: 'LIBRARY',
    },
    {
      id: 25,
      name: 'Node.js',
      skills: ['Event Loop', 'Express Integration', 'npm Modules'],
      urlLogo: 'assets/img/logos/platform/nodejs.svg',
      isLearning: false,
      type: 'PLATFORM',
    },
    {
      id: 26,
      name: 'Prettier',
      skills: ['Formato Código', 'Integracion con IDEs', 'Reglas personalizadas'],
      urlLogo: 'assets/img/logos/tool/prettier.svg',
      isLearning: false,
      type: 'TOOL',
    },
    {
      id: 27,
      name: 'Express.js',
      skills: ['Routing', 'Middlewares', 'REST APIs'],
      urlLogo: 'assets/img/logos/framework/expressjs.svg',
      isLearning: false,
      type: 'FRAMEWORK',
    },
  ],
  yearsXP: 3,
  numberPhone: '2944-716770',
};
